create extension if not exists pgcrypto;

create table if not exists public.cover_pick_winners (
  id uuid primary key default gen_random_uuid(),
  identity_hash text not null,
  submitted boolean not null default false,
  submitted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_attendees (
  id uuid primary key default gen_random_uuid(),
  winner_id uuid not null references public.cover_pick_winners(id) on delete cascade,
  name text not null,
  nationality text not null,
  birth_date date not null,
  phone text not null,
  contact_email text not null,
  consent_version text not null,
  consented_at timestamptz not null,
  account_email text not null,
  muniverse_nickname text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_verification_sessions (
  id uuid primary key default gen_random_uuid(),
  winner_id uuid not null references public.cover_pick_winners(id) on delete cascade,
  stage text not null,
  token_hash text not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  ip_hash text,
  user_agent_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  action text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_audit_log (
  id bigint generated by default as identity primary key,
  event text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
