-- Split the public winner-verification load from the protected attendee-registration load
-- while keeping the existing Supabase project, database, and single-page frontend.

alter table public.cover_pick_verification_sessions
  add column if not exists account_email text,
  add column if not exists muniverse_nickname text,
  add column if not exists token_version smallint not null default 1;

create table if not exists public.cover_pick_verify_rate_limits (
  id bigint generated by default as identity primary key,
  rate_key text not null,
  action text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_register_rate_limits (
  id bigint generated by default as identity primary key,
  rate_key text not null,
  action text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_verify_audit_log (
  id bigint generated by default as identity primary key,
  event text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.cover_pick_register_audit_log (
  id bigint generated by default as identity primary key,
  event text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists cover_pick_verify_rate_lookup_idx
  on public.cover_pick_verify_rate_limits(rate_key, action, created_at desc);
create index if not exists cover_pick_verify_rate_action_idx
  on public.cover_pick_verify_rate_limits(action, created_at desc);
create index if not exists cover_pick_register_rate_lookup_idx
  on public.cover_pick_register_rate_limits(rate_key, action, created_at desc);
create index if not exists cover_pick_register_rate_action_idx
  on public.cover_pick_register_rate_limits(action, created_at desc);
create index if not exists cover_pick_verify_audit_created_idx
  on public.cover_pick_verify_audit_log(created_at desc);
create index if not exists cover_pick_register_audit_created_idx
  on public.cover_pick_register_audit_log(created_at desc);

alter table public.cover_pick_verify_rate_limits enable row level security;
alter table public.cover_pick_register_rate_limits enable row level security;
alter table public.cover_pick_verify_audit_log enable row level security;
alter table public.cover_pick_register_audit_log enable row level security;

revoke all on public.cover_pick_verify_rate_limits from anon, authenticated;
revoke all on public.cover_pick_register_rate_limits from anon, authenticated;
revoke all on public.cover_pick_verify_audit_log from anon, authenticated;
revoke all on public.cover_pick_register_audit_log from anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cover_pick_session_identity_lengths_ck') THEN
    ALTER TABLE public.cover_pick_verification_sessions
      ADD CONSTRAINT cover_pick_session_identity_lengths_ck
      CHECK (
        (account_email is null or char_length(account_email) between 3 and 254)
        and (muniverse_nickname is null or char_length(muniverse_nickname) between 1 and 80)
        and token_version between 1 and 99
      );
  END IF;
END $$;

create or replace function public.cleanup_cover_pick_operational_data()
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  delete from public.cover_pick_verification_sessions
   where expires_at < now() - interval '1 day'
      or (used = true and created_at < now() - interval '1 day');

  delete from public.cover_pick_rate_limits
   where created_at < now() - interval '24 hours';
  delete from public.cover_pick_verify_rate_limits
   where created_at < now() - interval '24 hours';
  delete from public.cover_pick_register_rate_limits
   where created_at < now() - interval '24 hours';

  delete from public.cover_pick_audit_log
   where created_at < now() - interval '30 days';
  delete from public.cover_pick_verify_audit_log
   where created_at < now() - interval '30 days';
  delete from public.cover_pick_register_audit_log
   where created_at < now() - interval '30 days';
end;
$$;

revoke all on function public.cleanup_cover_pick_operational_data() from public, anon, authenticated;
